
# ::::::::::::::::::::::
# ::: Graphic config :::
# ::::::::::::::::::::::
[window]
decorations = "none"
#padding = { x = 5, y = 5 }

[font]
# All styles inherits from the "normal" family if not specified otherwise.
normal = { family = 'JetBrainsMonoNL Nerd Font Mono', style = 'Regular' }
size = 16

[cursor]
vi_mode_style = { shape = 'Underline', blinking = 'Always' }

# :::::::::::::::::::
# ::: Color Theme :::
# :::::::::::::::::::
# alacritty's themes repos :
# https://github.com/alacritty/alacritty-theme
[general]
import = [
	'~/Documents/42_config/alacritty/themes/enfocado_light.toml'
	#'~/Documents/42_config/alacritty/themes/enfocado_dark.toml'
]
